name=Umbra
version=${version}
additionalVersions=
className=com.gtnewhorizons.umbra.loading.rfb.UmbraRfbPlugin
transformerExclusions=com.gtnewhorizons.umbra.loading.shared;com.gtnewhorizon.gtnhlib.asm
versionConstraints=
loadBefore=
loadAfter=mixin; lwjgl3ify
loadRequires=
